[project]
name = "piepaybot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
piepaybot = "piepaybot:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
